apiVersion: v1
kind: Namespace
metadata:
  name: outline
---
apiVersion: v1
kind: Secret
metadata:
  name: outline-secret
  namespace: outline
type: Opaque
data:
  database-url: "${OUTLINE_DATABASE_URL}"
  discord-client-secret: "${OUTLINE_DISCORD_CLIENT_SECRET}"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: outline-pv
spec:
  storageClassName: outline-pv
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/outline-data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: outline-pvc
  namespace: outline
spec:
  storageClassName: outline-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: outline-config
  namespace: outline
data:
  NODE_ENV: production
  REDIS_URL: redis://redis-service.redis:6379
  FILE_STORAGE: local
  FILE_STORAGE_LOCAL_ROOT_DIR: /var/lib/outline/data
  PGSSLMODE: disable
  URL: https://${OUTLINE_HOST}
  SECRET_KEY: ${OUTLINE_SECRET_KEY}
  UTILS_SECRET: ${OUTLINE_UTILS_SECRET}
  FORCE_HTTPS: "false"
  DISCORD_CLIENT_ID: "${OUTLINE_DISCORD_CLIENT_ID}"
  DISCORD_SERVER_ID: "${OUTLINE_DISCORD_SERVER_ID}"
  DISCORD_SERVER_ROLES: "${OUTLINE_DISCORD_SERVER_ROLES}"
  DISCORD_CLIENT_SECRET: "${OUTLINE_DISCORD_CLIENT_SECRET}"
  CDN_URL: https://${OUTLINE_HOST}
  LOG_LEVEL: debug
  TRUST_PROXY: "1"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: outline
  namespace: outline
spec:
  selector:
    matchLabels:
      app: outline
  template:
    metadata:
      labels:
        app: outline
    spec:
      containers:
        - name: outline
          image: docker.getoutline.com/outlinewiki/outline:latest
          envFrom:
            - configMapRef:
                name: outline-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: outline-secret
                  key: database-url
            - name: DISCORD_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: outline-secret
                  key: discord-client-secret
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: outline-storage
              mountPath: /data
      volumes:
        - name: outline-storage
          persistentVolumeClaim:
            claimName: outline-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: outline
  namespace: outline
spec:
  type: ClusterIP
  selector:
    app: outline
  ports:
    - name: http
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: outline-allow-web
  namespace: outline
spec:
  podSelector:
    matchLabels:
      app: outline
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {}
          podSelector: {}
      ports:
        - protocol: TCP
          port: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: outline-ingress
  namespace: outline
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - host: ${OUTLINE_HOST}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: outline
                port:
                  number: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: outline-hpa
  namespace: outline
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: outline
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 90
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 80
      policies:
        - type: Percent
          value: 100
          periodSeconds: 60
        - type: Pods
          value: 10
          periodSeconds: 60
      selectPolicy: Max
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 2
          periodSeconds: 15
      selectPolicy: Max
